<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><OutputType>Library</OutputType><RootNamespace>GDMCore</RootNamespace><AssemblyName>GDMCore</AssemblyName><GenerateDocumentationFile>true</GenerateDocumentationFile><Nullable>disable</Nullable><LangVersion>latest</LangVersion><Platforms>AnyCPU;x86</Platforms><AllowUnsafeBlocks>false</AllowUnsafeBlocks><GenerateAssemblyInfo>false</GenerateAssemblyInfo></PropertyGroup><ItemGroup><PackageReference Include="MathNet.Numerics.Signed" Version="5.0.0" /></ItemGroup><ItemGroup><ProjectReference Include="..\GDMInterfaces\GDMInterfaces.csproj" /></ItemGroup></Project>
