//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace GDMPlugins
{ // 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Distribution {
    
        private string nameField;
    
        private DistributionDistributionParameter[] distributionParameterField;
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("DistributionParameter", Form=XmlSchemaForm.Unqualified)]
        public DistributionDistributionParameter[] DistributionParameter {
            get {
                return this.distributionParameterField;
            }
            set {
                this.distributionParameterField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class DistributionDistributionParameter {
    
        private string nameField;
    
        private string valueField;
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Resource {
    
        private string resourceIdentifierField;
    
        private string identifierField;
    
        private string nameField;
    
        private string resourceTypeField;
    
        private string resourceDescriptionField;
    
        private ResourceProperty[] propertyField;
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string ResourceIdentifier {
            get {
                return this.resourceIdentifierField;
            }
            set {
                this.resourceIdentifierField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string ResourceType {
            get {
                return this.resourceTypeField;
            }
            set {
                this.resourceTypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string ResourceDescription {
            get {
                return this.resourceDescriptionField;
            }
            set {
                this.resourceDescriptionField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Property", Form=XmlSchemaForm.Unqualified)]
        public ResourceProperty[] Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
    }


    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class PartType
    {

        private string identifierField;

        private string partTypeDescriptionField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }


        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return this.partTypeDescriptionField;
            }
            set
            {
                this.partTypeDescriptionField = value;
            }
        }

    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class Schedule
    {
        private string _startTimeField;
        private string _descriptionField;
        private string _endTimeField;
        private ScheduleItem[] _scheduleItemsField;
        private string _identifierField;

        /// <remarks/>
        
        [XmlElement(Form = XmlSchemaForm.Unqualified)]
        public string Identifier
        {
            get
            {
                return this._identifierField;
            }
            set
            {
                this._identifierField = value;
            }
        }


        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return this._descriptionField;
            }
            set
            {
                this._descriptionField = value;
            }
        }


        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified)]
        public string StartTime
        {
            get
            {
                return this._startTimeField;
            }
            set
            {
                this._startTimeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified)]
        public string EndTime
        {
            get
            {
                return this._endTimeField;
            }
            set
            {
                this._endTimeField = value;
            }
        }
        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified)]
        public ScheduleItem[] ScheduleItem
        {
            get
            {
                return this._scheduleItemsField;
            }
            set
            {
                this._scheduleItemsField = value;
            }
        }

    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class ScheduleItem
    {
        
        private string _assosiatedJobField;
        
        private string _identifierField;

        /// <remarks/>

        [XmlElement(Form = XmlSchemaForm.Unqualified)]
        public string Identifier
        {
            get { return this._identifierField; }
            set { this._identifierField = value; }
        }


        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified)]
        public string AssosiatedJob
        {
            get { return this._assosiatedJobField; }
            set { this._assosiatedJobField = value; }
        }
    }

    /// <remarks/>
        [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class ResourceProperty {
    
        private string nameField;
    
        private string descriptionField;
    
        private string unitField;
    
        private string valueField;
    
        private Distribution[] distributionField;
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Distribution")]
        public Distribution[] Distribution {
            get {
                return this.distributionField;
            }
            set {
                this.distributionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class CMSDDocument {
    
        private object[] itemsField;
    
        /// <remarks/>
        [XmlElement("DataSection", typeof(CMSDDocumentDataSection), Form=XmlSchemaForm.Unqualified)]
        [XmlElement("Distribution", typeof(Distribution))]
        [XmlElement("Resource", typeof(Resource))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class CMSDDocumentDataSection {
    
        private CMSDDocumentDataSectionJob[] jobField;
    
        private Resource[] resourceField;

        private PartType[] partTypeField;

        private Schedule[] _schedule;
    
        /// <remarks/>
        [XmlElement("Job", Form=XmlSchemaForm.Unqualified)]
        public CMSDDocumentDataSectionJob[] Job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Resource")]
        public Resource[] Resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }

        /// <remarks/>
        [XmlElement("PartType")]
        public PartType[] PartType
        {
            get
            {
                return this.partTypeField;
            }
            set
            {
                this.partTypeField = value;
            }
        }
        /// <remarks/>
        [XmlElement("Schedule")]
        public Schedule[] Schedule
        {
            get { return this._schedule; }
            set
            {
                this._schedule = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class CMSDDocumentDataSectionJob {
    
        private string identifierField;
    
        private string descriptionField;
    
        private CMSDDocumentDataSectionJobSubJob[] subJobField;
    
        private CMSDDocumentDataSectionJobPlannedEffort[] plannedEffortField;
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("SubJob", Form=XmlSchemaForm.Unqualified)]
        public CMSDDocumentDataSectionJobSubJob[] SubJob {
            get {
                return this.subJobField;
            }
            set {
                this.subJobField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("PlannedEffort", Form=XmlSchemaForm.Unqualified)]
        public CMSDDocumentDataSectionJobPlannedEffort[] PlannedEffort {
            get {
                return this.plannedEffortField;
            }
            set {
                this.plannedEffortField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class CMSDDocumentDataSectionJobSubJob {
    
        private string jobIdentifierField;
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string JobIdentifier {
            get {
                return this.jobIdentifierField;
            }
            set {
                this.jobIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class CMSDDocumentDataSectionJobPlannedEffort {
    
        private CMSDDocumentDataSectionJobPlannedEffortProcessingTime[] processingTimeField;
    
        private CMSDDocumentDataSectionJobPlannedEffortPartType[] partTypeField;
    
        private Resource[] resourcesRequiredField;
        private CMSDDocumentDataSectionJobPlannedEffortPartType[] partTypeProducedField;
        private CMSDDocumentDataSectionJobPlannedEffortPartType[] partTypeConsumedField;

        /// <remarks/>
        [XmlElement("ProcessingTime", Form=XmlSchemaForm.Unqualified)]
        public CMSDDocumentDataSectionJobPlannedEffortProcessingTime[] ProcessingTime {
            get {
                return this.processingTimeField;
            }
            set {
                this.processingTimeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("PartTypeProduced", Form=XmlSchemaForm.Unqualified)]
        public CMSDDocumentDataSectionJobPlannedEffortPartType[] PartTypeProduced {
            get {
                return this.partTypeProducedField;
            }
            set {
                this.partTypeProducedField = value;
            }
        }

        /// <remarks/>
        [XmlElement("PartTypeConsumed", Form = XmlSchemaForm.Unqualified)]
        public CMSDDocumentDataSectionJobPlannedEffortPartType[] PartTypeConsumed
        {
            get
            {
                return this.partTypeConsumedField;
            }
            set
            {
                this.partTypeConsumedField = value;
            }
        }

        /// <remarks/>
        [XmlArray(Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItem("Resource", typeof(Resource), IsNullable=false)]
        public Resource[] ResourcesRequired {
            get {
                return this.resourcesRequiredField;
            }
            set {
                this.resourcesRequiredField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class CMSDDocumentDataSectionJobPlannedEffortProcessingTime {
    
        private string timeUnitField;
    
        private Distribution[] distributionField;
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string TimeUnit {
            get {
                return this.timeUnitField;
            }
            set {
                this.timeUnitField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Distribution")]
        public Distribution[] Distribution {
            get {
                return this.distributionField;
            }
            set {
                this.distributionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class CMSDDocumentDataSectionJobPlannedEffortPartType {
    
        private string partTypeIdentifierField;
      
    
        /// <remarks/>
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string PartTypeIdentifier {
            get {
                return this.partTypeIdentifierField;
            }
            set {
                this.partTypeIdentifierField = value;
            }
        }

    }

}