<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Library</OutputType>
    <RootNamespace>GDMPlugins</RootNamespace>
    <AssemblyName>GDMPlugins</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x86</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Accord" Version="3.8.0" />
    <PackageReference Include="Accord.Math" Version="3.8.0" />
    <PackageReference Include="Accord.Statistics" Version="3.8.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.4.1" />
    <PackageReference Include="ExcelDataReader" Version="3.8.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
    <PackageReference Include="LibOptimization" Version="1.14.0" />
    <PackageReference Include="MathNet.Numerics.Signed" Version="5.0.0" />
    <PackageReference Include="Meta.Numerics" Version="4.2.0" />
    <PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.Winforms" Version="150.1652.0" />
    <PackageReference Include="Microsoft.SqlServer.Types" Version="170.1000.7" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="System.Data.OleDb" Version="10.0.3" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="ZedGraph" Version="5.2.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GDMCore\GDMCore.csproj" />
    <ProjectReference Include="..\GDMInterfaces\GDMInterfaces.csproj" />
  </ItemGroup>
</Project>
